services:
  quartz_server:
    image: quartz_server
    container_name: quartz_server
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      QUARTZ_CONTENT_REPOSITORY_URL: 
      NGINX_SERVER_NAME: 
      NGINX_BASE_PATH: /quartz
    networks:
      - delevate
    ports:
      - "81:80"

networks:
  delevate:
    external: true
    name: delevate

