#!/bin/bash

printenv | grep "QUARTZ_CONTENT_REPOSITORY_URL" >> /etc/environment

echo "----- Starting initial quartz build ------"
/bin/bash /app/build_quartz_pages 

echo "----- Starting nginx & Listening to cron job ------"

/usr/sbin/nginx -g "daemon off;" &

cron && tail -f /var/log/cron.log &
wait
